[workspace]

members = [ "bin/rei","crates/condensed", "crates/primitives", "crates/runtime", "crates/server", "crates/tracker"]

default-member = ["bin/rei"]

resolver = "2"

[workspace.dependencies]
