[package]
name = "condensed"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
ez-ffmpeg = "0.4.1" 
rayon = "1.10.0"
srtparse = "0.2.0"
rand = "0.9.1"
clap = { version = "4.5.38", features = ["derive"] }
dotenv = "0.15.0"

